# Hyprpaper Config (Modern block syntax for v0.8.4+)
preload = /home/levi/.config/themes/space/blackholeBG.jpg

wallpaper {
    monitor = DP-2
    path = /home/levi/.config/themes/space/blackholeBG.jpg
    fit_mode = cover
}

splash = false
ipc = on
