# Hyprpaper Config (Modern block syntax for v0.8.4+)
preload = /home/levi/.config/themes/current/background.jpg

wallpaper {
    monitor = 
    path = /home/levi/.config/themes/current/background.jpg
    fit_mode = cover
}

splash = false
ipc = on
