$primary = rgba(d8c7a5ff)
$on_primary = rgba(11130fff)
$primary_container = rgba(d8c7a52e)
$background = rgba(11130fd9)
$surface = rgba(2b251d99)
$text = rgba(e6e1e5ff)
$subtext = rgba(a6afb7ff)
$border = rgba(ffffff14)
$warning = rgba(fab387ff)
$critical = rgba(f38ba8ff)
$font_family = Comfortaa
$font_family_bold = Comfortaa Bold
