$primary = rgba(d0bcffff)
$on_primary = rgba(07001fff)
$primary_container = rgba(d0bcff2e)
$background = rgba(07001fb8)
$surface = rgba(18122bad)
$text = rgba(e6e1e5ff)
$subtext = rgba(cac4d0ff)
$border = rgba(d0bcff47)
$font_family = Comfortaa
$font_family_bold = Comfortaa Bold
